version: 2.1

commands:
  install_deps:
    description: "Install project dependencies"
    steps:
      - run: yarn
      - run: cd packages/ds && yarn
      - run: cd packages/util && yarn

jobs:
  lint_and_format_check:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - install_deps
      - run: yarn lint
      - run: yarn format-check
  compile:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - install_deps
      - run: rm -rf packages/ds/lib
      - run: rm -rf packages/util/lib
      - run: yarn build
  test:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - install_deps
      - run: cd packages/ds && yarn test
      - run: cd packages/util && yarn test

workflows:
  build_and_test:
    jobs:
      - lint_and_format_check
      - compile
      - test:
          requires:
            - compile
            - lint_and_format_check
